
//Error Handling
//Error at row level-----Remove row
let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    ChangedType = Table.TransformColumnTypes(Source,{"Età", type number})
    in
    ChangedType

let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    ChangedType = Table.TransformColumnTypes(Source,{"Età", type number}),
    RemovedErrors = Table.RemoveRowsWithErrors(ChangedType)
in
    RemovedErrors


//Details Error at row level-----
let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    ChangedType = Table.TransformColumnTypes(Source, {"Età", type number}),
    #"Inserted Eta_Try" = Table.AddColumn(ChangedType, "Eta_Try", each try [Età]),
    #"Expand Eta_Try" = Table.ExpandRecordColumn(#"Inserted Eta_Try", "Eta_Try", {"HasError", "Value", "Error"}, {"Eta_Try.HasError", "Eta_Try.Value", "Eta_Try.Error"})
in
    #"Expand Eta_Try"


//Direct error handling with only Try
let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    InsertedCustom = Table.AddColumn(Source, "Età_Bis", each try Number.From([Età])
in
    InsertedCustom


//Direct error handling with otherwise
let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    InsertedCustom = Table.AddColumn(Source, "Età_Bis", each try Number.From([Età]) otherwise 0)
in
    InsertedCustom